import jsPDF from 'jspdf';

export const generateInspectionReport = (data, options = {}) => {
  const { inspectionId, filename, imageDataUrl } = options || {};

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  const safeData = data || {};
  const damages = safeData.detected_damages || {};
  const precautions = Array.isArray(safeData.precautions) ? safeData.precautions : [];
  const severity = safeData.severity || "Moderate";
  const healthScore = typeof safeData.health_score === "number" ? safeData.health_score : 0;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(40, 53, 147);
  doc.text('Smart Building Inspection Report', pageWidth / 2, 20, { align: 'center' });

  // Date / meta
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  const now = new Date();
  doc.text(`Report Date: ${now.toLocaleDateString()}`, 20, 40);
  doc.text(`Report Time: ${now.toLocaleTimeString()}`, 20, 48);

  if (inspectionId) doc.text(`Inspection ID: ${inspectionId}`, 20, 56);
  if (filename) doc.text(`File: ${filename}`, 20, 64);

  let yPos = filename || inspectionId ? 78 : 60;

  // Optional image embed (expects a base64 data URL like "data:image/jpeg;base64,...")
  if (imageDataUrl) {
    try {
      // Guess format from data URL
      const isPng = imageDataUrl.startsWith("data:image/png");
      const format = isPng ? "PNG" : "JPEG";

      // Fit image in page width with margins
      const imgX = 20;
      const imgW = pageWidth - 40;
      const imgH = 60;

      doc.setFontSize(12);
      doc.text("Analyzed Image:", 20, yPos);
      yPos += 6;

      doc.addImage(imageDataUrl, format, imgX, yPos, imgW, imgH); // jsPDF addImage API [web:408]
      yPos += imgH + 12;
    } catch (e) {
      // If image fails, just continue
      yPos += 10;
    }
  }

  // Damage summary
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Damage Analysis Summary', 20, yPos);
  yPos += 12;

  doc.setFontSize(12);

  if (Object.keys(damages).length === 0) {
    doc.text('No damages detected - Building is in good condition', 25, yPos);
    yPos += 10;
  } else {
    Object.entries(damages).forEach(([damage, count]) => {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
      const damageName = String(damage).replaceAll('_', ' ').toUpperCase();
      doc.text(`• ${damageName}: ${count} instance(s)`, 25, yPos);
      yPos += 8;
    });
  }

  yPos += 8;

  // Severity + score
  doc.setFontSize(16);
  doc.text('Building Health Assessment', 20, yPos);
  yPos += 12;

  doc.setFontSize(12);
  doc.text(`Severity Level: ${severity}`, 25, yPos);
  yPos += 8;
  doc.text(`Health Score: ${healthScore}/100`, 25, yPos);
  yPos += 12;

  // Precautions (wrapped)
  doc.setFontSize(16);
  doc.text('Recommended Actions', 20, yPos);
  yPos += 12;

  doc.setFontSize(12);
  if (precautions.length === 0) {
    doc.text('No recommendations available.', 25, yPos);
    yPos += 8;
  } else {
    precautions.forEach((precaution, index) => {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }

      const text = `${index + 1}. ${precaution}`;
      const lines = doc.splitTextToSize(text, pageWidth - 50); // wrap long text [web:411]
      doc.text(lines, 25, yPos);
      yPos += lines.length * 7;
    });
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Smart Building Inspection System', pageWidth / 2, 290, { align: 'center' });
  doc.text('Final Year Project | mAP: 89%', pageWidth / 2, 295, { align: 'center' });

  // Save
  const fileNameOut = `building-inspection-${inspectionId || Date.now()}.pdf`;
  doc.save(fileNameOut); // jsPDF save() [web:415]
  return fileNameOut;
};
